export const accountTypes = {
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
};

export const feedsTypes = {
	GET_FEEDS: 'GET_FEEDS',
	POST_FEED: 'POST_FEED',
	UPDATE_FEED: 'UPDATE_FEED',
};

export const formsTypes = {
	GET_FORMS: 'GET_FORMS',
	POST_FORM: 'POST_FORM',
	UPDATE_FORM: 'UPDATE_FORM',
};

export const lessonsTypes = {
	GET_LESSONS: 'GET_LESSONS',
	POST_LESSON: 'POST_LESSON',
	UPDATE_LESSON: 'UPDATE_LESSON',
};

export const checklistsTypes = {
	GET_CHECKLISTS: 'GET_CHECKLISTS',
	POST_CHECKLIST: 'POST_CHECKLIST',
	UPDATE_CHECKLIST: 'UPDATE_CHECKLIST',
};

export const viewTypes = {
	SET_APPBAR_TITLE: 'SET_APPBAR_TITLE',
	TOGGLE_LESSONS_MENU: 'TOGGLE_LESSONS_MENU',
};