export const accountTypes = {
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
};

export const feedsTypes = {
	GET_FEEDS: 'GET_FEEDS',
};

export const formsTypes = {
	GET_FORM_TYPES: 'GET_FORM_TYPES',
	GET_FORMS: 'GET_FORMS',
	POST_FORM: 'POST_FORM',
	RESET_POST_FORM: 'RESET_POST_FORM',
	UPDATE_FORM: 'UPDATE_FORM',
};

export const lessonsTypes = {
	GET_LESSONS: 'GET_LESSONS',
	SET_LESSON: 'SET_LESSON',
};

export const checklistsTypes = {
	GET_SYSTEM_CHECKLISTS: 'GET_SYSTEM_CHECKLISTS',
	GET_CUSTOM_CHECKLISTS: 'GET_CUSTOM_CHECKLISTS',
};

export const viewTypes = {
	TOGGLE_MAIN_MENU: 'TOGGLE_MAIN_MENU',
	SET_APPBAR_TITLE: 'SET_APPBAR_TITLE',
	TOGGLE_LESSONS_MENU: 'TOGGLE_LESSONS_MENU',
	SET_LESSONS_CONTENT_TYPE: 'SET_LESSONS_CONTENT_TYPE',
	SET_LESSONS_CONTENT_PATH: 'SET_LESSONS_CONTENT_PATH',
	SET_LOCALE: 'SET_LOCALE',
};