export const contentTypes = {
	GET_CONTENT: 'GET_CONTENT',
}

export const accountTypes = {
	LOGIN: 'LOGIN',
	CHECK_PASSWORD: 'CHECK_PASSWORD',
	SAVE_PASSWORD: 'SAVE_PASSWORD',
}

export const feedsTypes = {
	GET_FEEDS: 'GET_FEEDS',
	SET_FEED_LOCATION: 'SET_FEED_LOCATION',
	SET_FEED_SOURCES: 'SET_FEED_SOURCES',
	GET_RSS: 'GET_RSS',
	ADD_RSS_SOURCE: 'ADD_RSS_SOURCE',
	SYNC_FEEDS: 'SYNC_FEEDS',
}

export const formsTypes = {
	GET_FORM: 'GET_FORM',
	POST_FORM: 'POST_FORM',
	RESET_POST_FORM: 'RESET_POST_FORM',
	SYNC_FORMS: 'SYNC_FORMS',
}

export const lessonsTypes = {
	SET_LESSON: 'SET_LESSON',
	GET_LESSON_CHECKLIST: 'GET_LESSON_CHECKLIST',
	GET_LESSON_FILE: 'GET_LESSON_FILE',
	CLOSE_LESSON: 'CLOSE_LESSON',
	CLOSE_LESSON_FILE: 'CLOSE_LESSON_FILE',
	RESET_LESSONS: 'RESET_LESSONS',
}

export const checklistsTypes = {
	GET_CHECKLISTS_SYSTEM: 'GET_CHECKLISTS_SYSTEM',
	GET_CHECKLISTS_CUSTOM: 'GET_CHECKLISTS_CUSTOM',
	SYNC_CHECKLISTS: 'SYNC_CHECKLISTS',
}

export const viewTypes = {
	TOGGLE_MAIN_MENU: 'TOGGLE_MAIN_MENU',
	SET_APPBAR_TITLE: 'SET_APPBAR_TITLE',
	TOGGLE_LESSONS_MENU: 'TOGGLE_LESSONS_MENU',
	SET_LESSONS_CONTENT_TYPE: 'SET_LESSONS_CONTENT_TYPE',
	SET_LESSONS_CONTENT_PATH: 'SET_LESSONS_CONTENT_PATH',
	TOGGLE_LESSONS_FAVORITES_VIEW: 'TOGGLE_LESSONS_FAVORITES_VIEW',
	TOGGLE_LESSON_FILE_VIEW: 'TOGGLE_LESSON_FILE_VIEW',
	CLOSE_LESSON_FILE_VIEW: 'CLOSE_LESSON_FILE_VIEW',
	RESET_LESSONS: 'RESET_LESSONS',
	SET_LOCALE: 'SET_LOCALE',
}

export const dbTypes = {
	SYNC_DB: 'SYNC_DB',
}